### ISSUE TITLE
Failure to Run duskhaven_launcher.bin [Garuda Linux, Arch Derivative]

### ISSUE THREAD

**Issue by jimmon89** [chtheiss/duskhaven_launcher#9]
When trying to run duskhaven_launcher.bin from the terminal it shows this error
```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, wayland, wayland-egl, vnc, vkkhrdisplay, offscreen, minimalegl, minimal, linuxfb, eglfs.
```
and when trying to run it with the env variable `QT_DEBUG_PLUGINS=1` set it dumps out this
```
qt.core.plugin.factoryloader: checking directory path "/tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms" ...
qt.core.plugin.factoryloader: looking at "/tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqxcb.so"
qt.core.plugin.loader: Found metadata in lib /tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archlevel": 1,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("xcb")
qt.core.plugin.factoryloader: looking at "/tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqwayland-generic.so"
qt.core.plugin.loader: Found metadata in lib /tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqwayland-generic.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland"
        ]
    },
    "archlevel": 1,
    "className": "QWaylandIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("wayland")
qt.core.plugin.factoryloader: looking at "/tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqwayland-egl.so"
qt.core.plugin.loader: Found metadata in lib /tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqwayland-egl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland-egl"
        ]
    },
    "archlevel": 1,
    "className": "QWaylandEglPlatformIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("wayland-egl")
qt.core.plugin.factoryloader: looking at "/tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqvnc.so"
qt.core.plugin.loader: Found metadata in lib /tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqvnc.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vnc"
        ]
    },
    "archlevel": 1,
    "className": "QVncIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("vnc")
qt.core.plugin.factoryloader: looking at "/tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqvkkhrdisplay.so"
qt.core.plugin.loader: Found metadata in lib /tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqvkkhrdisplay.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vkkhrdisplay"
        ]
    },
    "archlevel": 1,
    "className": "QVkKhrDisplayIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("vkkhrdisplay")
qt.core.plugin.factoryloader: looking at "/tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqoffscreen.so"
qt.core.plugin.loader: Found metadata in lib /tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "archlevel": 1,
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("offscreen")
qt.core.plugin.factoryloader: looking at "/tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqminimalegl.so"
qt.core.plugin.loader: Found metadata in lib /tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "archlevel": 1,
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("minimalegl")
qt.core.plugin.factoryloader: looking at "/tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqminimal.so"
qt.core.plugin.loader: Found metadata in lib /tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "archlevel": 1,
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("minimal")
qt.core.plugin.factoryloader: looking at "/tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqlinuxfb.so"
qt.core.plugin.loader: Found metadata in lib /tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqlinuxfb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "linuxfb"
        ]
    },
    "archlevel": 1,
    "className": "QLinuxFbIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("linuxfb")
qt.core.plugin.factoryloader: looking at "/tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqeglfs.so"
qt.core.plugin.loader: Found metadata in lib /tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "archlevel": 1,
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 394496
}


qt.core.plugin.factoryloader: Got keys from plugin meta data QList("eglfs")
qt.core.plugin.factoryloader: checking directory path "/tmp/onefile_1467255_1680974875_180718/platforms" ...
qt.core.library: "/tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqxcb.so" cannot load: Cannot load library /tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqxcb.so: (/usr/lib/libQt6XcbQpa.so.6: undefined symbol: _ZN22QWindowSystemInterface22handleExtendedKeyEventEP7QWindowmN6QEvent4TypeEi6QFlagsIN2Qt16KeyboardModifierEEjjjRK7QStringbtb, version Qt_6_PRIVATE_API)
qt.core.plugin.loader: QLibraryPrivate::loadPlugin failed on "/tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqxcb.so" : "Cannot load library /tmp/onefile_1467255_1680974875_180718/PySide6/qt-plugins/platforms/libqxcb.so: (/usr/lib/libQt6XcbQpa.so.6: undefined symbol: _ZN22QWindowSystemInterface22handleExtendedKeyEventEP7QWindowmN6QEvent4TypeEi6QFlagsIN2Qt16KeyboardModifierEEjjjRK7QStringbtb, version Qt_6_PRIVATE_API)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, wayland, wayland-egl, vnc, vkkhrdisplay, offscreen, minimalegl, minimal, linuxfb, eglfs.
```

**Comment by chtheiss** [comment]
Ahh I see. Thanks for reporting this. It seems that this is a common issue when building python and qt related binaries with github actions.
This commit [Update linux_build.yml](https://github.com/chtheiss/duskhaven_launcher/commit/d694f3e80042963a4770aa57e3e96432cc1bccf1) should resolve the issue.

This [issue](https://github.com/Nuitka/Nuitka/issues/2138) in the official Nuitka repo for reference. 

I tried it on my Ubuntu laptop and the launcher starts without issues now. You might need to do `chmod +x duskhaven_launcher.bin`

I just updated the .bin file in the [0.1.1 release](https://github.com/chtheiss/duskhaven_launcher/releases/tag/v0.1.1). So you can redownload it there.

Let me know if this resolved your issue. :)

**Comment by jimmon89** [comment]
downloading the updated bin now, will report back

**Comment by jimmon89** [comment]
new problem now, if you'd prefer i can make a new ticket
```
Traceback (most recent call last):
  File "/tmp/onefile_1881064_1680984863_663630/duskhaven_launcher.py", line 567, in start_game
  File "/tmp/onefile_1881064_1680984863_663630/subprocess.py", line 969, in __init__
  File "/tmp/onefile_1881064_1680984863_663630/subprocess.py", line 1845, in _execute_child
PermissionError: [Errno 13] Permission denied: PosixPath('/media/data/Steam/steamapps/common/Duskhaven/wow.exe')
```

**Comment by chtheiss** [comment]
At which point of the installation do you get that error? Could you share the launcher.log and config.json here? But I assume it seems like a permission problem. Maybe you could try `sudo ./duskhaven_launcher.bin`

**Comment by jimmon89** [comment]
#10 is a fix for the executable not running
let me know your thoughts on my changes
